# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b95e728684a9096916435c4aa4256cdcae4a698d4f77f9825bb6cd9621eda52f8eec6d5ce82e8c923c24f239411563b83c64c87a501bd7ad04a9c0d0e16b7e

test:
  secret_key_base: cc8be9363e559d3583887dee201a971acb0d8735881d7442769e144f51bb7ee958769cad092f586ad6600a2362ebf1fc9f2980e199ae57296955540ec8567333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
